repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.3
    hooks:
        # Run the linter with auto-fix
        -   id: ruff
            args: [ --fix ]
        # Run the formatter
        -   id: ruff-format