"""stock model

Revision ID: 87e383998b64
Revises: 
Create Date: 2024-04-11 00:17:06.798660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87e383998b64'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks_base',
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('uniq_code', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=5), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('exchange_symbol', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('uniq_code'),
    sa.UniqueConstraint('symbol', 'exchange_symbol', name='stocks_base_uniq')
    )
    op.create_table('stock_price',
    sa.Column('uniq_code', sa.String(length=100), nullable=False),
    sa.Column('value', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uniq_code'], ['stocks_base.uniq_code'], ),
    sa.PrimaryKeyConstraint('uniq_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_price')
    op.drop_table('stocks_base')
    # ### end Alembic commands ###
