"""initial migration

Revision ID: f1da36014162
Revises: 
Create Date: 2024-08-25 02:01:43.102570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1da36014162'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('all_base',
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('id', sa.String(length=100), nullable=False, comment='CIK, ISIN 등 식별코드'),
    sa.Column('uniq_code', sa.String(length=100), nullable=False, comment='내부 관리 코드'),
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='심볼 (MSFT 등)'),
    sa.Column('type', sa.String(length=5), nullable=False, comment='ETF/STOCK/ETN/INDEX'),
    sa.Column('country', sa.String(length=5), nullable=False, comment='국가코드, USA/KOR ...'),
    sa.Column('source', sa.String(length=30), nullable=False, comment='데이터 소스, S&P Global, SEC 등'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('uniq_code')
    )
    op.create_table('stock_info',
    sa.Column('uniq_code', sa.String(length=100), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('public_date', sa.DATE(), nullable=False),
    sa.Column('private_date', sa.DATE(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uniq_code'], ['all_base.uniq_code'], ),
    sa.PrimaryKeyConstraint('uniq_code')
    )
    op.create_table('us_stock_price',
    sa.Column('uniq_code', sa.String(length=100), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=5), nullable=False),
    sa.Column('high_p', sa.DECIMAL(precision=10, scale=5), nullable=False),
    sa.Column('low_p', sa.DECIMAL(precision=10, scale=5), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uniq_code'], ['all_base.uniq_code'], ),
    sa.UniqueConstraint('uniq_code', 'date', name='stock_price_uniq')
    )
    op.create_index('idx_stock_price_date_uniq_code', 'us_stock_price', ['uniq_code', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_stock_price_date_uniq_code', table_name='us_stock_price')
    op.drop_table('us_stock_price')
    op.drop_table('stock_info')
    op.drop_table('all_base')
    # ### end Alembic commands ###
