"""empty message

Revision ID: 4126ecabde75
Revises:
Create Date: 2025-07-14 02:09:49.523767

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4126ecabde75"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dart_report_path",
        sa.Column("year", sa.String(), nullable=False),
        sa.Column("period", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("year", "period", "type", name="pk_dart_report_path"),
    )
    op.create_table(
        "dim_company",
        sa.Column("ucode", sa.String(), nullable=False),
        sa.Column("kr_name", sa.String(), nullable=True),
        sa.Column("us_name", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("market", sa.String(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("country", sa.String(), nullable=False),
        sa.Column("isin", sa.String(), nullable=False),
        sa.Column("is_yn", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("ucode"),
    )
    op.create_table(
        "fact_stock_bs",
        sa.Column("ucode", sa.String(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("assets", sa.Numeric(precision=21, scale=0), nullable=True),
        sa.Column("liabilities", sa.Numeric(precision=21, scale=0), nullable=True),
        sa.Column("current_assets", sa.Numeric(precision=21, scale=0), nullable=True),
        sa.Column(
            "current_liabilities", sa.Numeric(precision=21, scale=0), nullable=True
        ),
        sa.Column(
            "cash_and_cash_equivalents",
            sa.Numeric(precision=21, scale=0),
            nullable=True,
        ),
        sa.Column("inventory", sa.Numeric(precision=21, scale=0), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("ucode", "date", name="pk_fact_stock_bs_date_ucode"),
    )
    op.create_table(
        "fact_stock_cf",
        sa.Column("ucode", sa.String(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column(
            "beginning_cash_flow", sa.Numeric(precision=21, scale=0), nullable=True
        ),
        sa.Column("end_cash_flow", sa.Numeric(precision=21, scale=0), nullable=True),
        sa.Column(
            "operating_cash_flow", sa.Numeric(precision=21, scale=0), nullable=True
        ),
        sa.Column(
            "investing_cash_flow", sa.Numeric(precision=21, scale=0), nullable=True
        ),
        sa.Column(
            "financing_cash_flow", sa.Numeric(precision=21, scale=0), nullable=True
        ),
        sa.Column(
            "exchange_rate_cash_flow", sa.Numeric(precision=21, scale=0), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("ucode", "date", name="pk_fact_stock_cf_date_ucode"),
    )
    op.create_table(
        "fact_stock_pl",
        sa.Column("ucode", sa.String(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("revenue", sa.Numeric(precision=21, scale=0), nullable=True),
        sa.Column(
            "operating_income_loss", sa.Numeric(precision=21, scale=0), nullable=True
        ),
        sa.Column("profit_loss", sa.Numeric(precision=21, scale=0), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("ucode", "date", name="pk_fact_stock_pl_date_ucode"),
    )
    op.create_table(
        "fact_stock_price",
        sa.Column("ucode", sa.String(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("volume", sa.Numeric(precision=21, scale=0), nullable=False),
        sa.Column("price", sa.Numeric(precision=21, scale=3), nullable=False),
        sa.Column("mkt_cap", sa.Numeric(precision=21, scale=3), nullable=False),
        sa.Column("list_shrs", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("ucode", name="pk_fact_stock_ucode_date"),
        sa.UniqueConstraint("ucode", "date", name="uk_fact_stock_ucode_date"),
    )
    op.create_table(
        "fact_stock_short_balance",
        sa.Column("ucode", sa.String(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("short_volume", sa.BigInteger(), nullable=False),
        sa.Column("short_ratio", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ucode"],
            ["dim_company.ucode"],
        ),
        sa.PrimaryKeyConstraint(
            "ucode", "date", name="pk_fact_stock_short_balance_date_ucode"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fact_stock_short_balance")
    op.drop_table("fact_stock_price")
    op.drop_table("fact_stock_pl")
    op.drop_table("fact_stock_cf")
    op.drop_table("fact_stock_bs")
    op.drop_table("dim_company")
    op.drop_table("dart_report_path")
    # ### end Alembic commands ###
