"""메세지1

Revision ID: ba395e7ef707
Revises: 41f1958b77e8
Create Date: 2025-02-17 02:33:21.890482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba395e7ef707'
down_revision: Union[str, None] = '41f1958b77e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_company',
    sa.Column('ucode', sa.String(), nullable=False),
    sa.Column('isin', sa.String(), nullable=False),
    sa.Column('kr_name', sa.String(), nullable=True),
    sa.Column('us_name', sa.String(), nullable=True),
    sa.Column('security_type', sa.String(), nullable=False),
    sa.Column('is_listed', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('ucode'),
    sa.UniqueConstraint('isin')
    )
    op.create_table('fact_stock',
    sa.Column('ucode', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('stock_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ucode'], ['dim_company.ucode'], ),
    sa.PrimaryKeyConstraint('ucode')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fact_stock')
    op.drop_table('dim_company')
    # ### end Alembic commands ###
