services:
  db:
    image: postgres:16.4
    environment:
      - POSTGRES_USER=api
      - POSTGRES_DB=api
      - POSTGRES_PASSWORD=api
    volumes:
      - /home/mari/vol/db:/var/lib/postgresql/data
    healthcheck:
        test: [ "CMD", "pg_isready", "-U", "api" ]
        interval: 10s
        retries: 5
        start_period: 5s
    ports:
      - "5432:5432"
    restart: always