services:
  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/data:/data

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: iceberg
      POSTGRES_PASSWORD: iceberg
      POSTGRES_DB: iceberg
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  spark:
    image: bitnami/spark:latest
    container_name: spark
    command: bin/spark-shell
    environment:
      SPARK_MASTER_HOST: spark-master
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 4G
    depends_on:
      - minio
      - postgres
    volumes:
      - ./spark:/opt/spark/work-dir