"""Initial migration

Revision ID: ed98aa8afcdb
Revises: 
Create Date: 2024-06-09 22:17:39.084902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed98aa8afcdb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks_base',
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('uniq_code', sa.String(length=100), nullable=False, comment='내부 관리 코드'),
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='심볼 (MSFT 등)'),
    sa.Column('type', sa.String(length=5), nullable=False, comment='ETF/STOCK/ETN'),
    sa.Column('exchange', sa.String(length=50), nullable=False, comment='거래소'),
    sa.Column('industry', sa.String(length=100), nullable=True, comment='산업'),
    sa.Column('industry_code', sa.String(length=10), nullable=True, comment='산업 코드'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('uniq_code')
    )
    op.create_table('stock_price',
    sa.Column('uniq_code', sa.String(length=100), nullable=False),
    sa.Column('value', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uniq_code'], ['stocks_base.uniq_code'], ),
    sa.PrimaryKeyConstraint('uniq_code'),
    sa.UniqueConstraint('uniq_code', 'date', name='stocks_price_uniq')
    )
    op.create_index('idx_stock_price_date_uniq_code', 'stock_price', ['uniq_code', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_stock_price_date_uniq_code', table_name='stock_price')
    op.drop_table('stock_price')
    op.drop_table('stocks_base')
    # ### end Alembic commands ###
